//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Checkpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ChatId { get; set; }
        public string Text { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> SenderId_UserId { get; set; }
        public Nullable<int> User_UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
